fusor ui - change to address asset compilation in koji using rhscl
Without this change, an error like the following is observed in the build.log:

TypeError: Cannot call method 'active' of undefined
(in /builddir/build/BUILDROOT/ruby193-rubygem-fusor_ui-0.0.1-1.el7.git.0.30b4a49.noarch/opt/rh/ruby193/root/usr/share/gems/gems/fusor_ui-0.0.1/app/assets/javascripts/fusor_ui/vendor-fusor.js)
/opt/rh/ruby193/root/usr/share/gems/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:34:in `rescue in block in eval'
/opt/rh/ruby193/root/usr/share/gems/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:28:in `block in eval'
/opt/rh/ruby193/root/usr/share/gems/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:80:in `block in lock'
/opt/rh/ruby193/root/usr/share/gems/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:78:in `call'
/opt/rh/ruby193/root/usr/share/gems/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:78:in `Locker'
/opt/rh/ruby193/root/usr/share/gems/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:78:in `lock'
/opt/rh/ruby193/root/usr/share/gems/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:27:in `eval'
/opt/rh/ruby193/root/usr/share/gems/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:19:in `exec'
/opt/rh/ruby193/root/usr/share/gems/gems/uglifier-1.2.6/lib/uglifier.rb:99:in `compile'
/opt/rh/ruby193/root/usr/share/gems/gems/actionpack-3.2.8/lib/sprockets/compressors.rb:74:in `compress'
...